export interface General{
    rucP?                    : string;
    razonSocialP?            : string;
    direccionP?              : string;
    ciudadP?                 : number;
    paisP?                   : number;
    emailP?                  : string;
    nomRlp?                  : string;
    paginaWp?                : string;
    idNaturaleza?            : number;
    actividadEconomicaP?     : string;
    nombrePagoBp?            : string;
    direccionBp?             : string;
    numeroBp?                : string;
    codigoAbabp?             : string;
    ciudadBp?                : number;
    paisBp?                  : number;
    tipoCbp?                 : string;
    codigoSwiftBp?           : string;
    nombreEmpP?              : string;
    cargoEmpP?               : string;
    aceptacionLeyenda?       : number;
    registroIp?              : string;
}
